#pragma once

typedef enum {
    TOKEN_PREPROCESSING, // 0
    TOKEN_VAR_INITIALIZER, // 1
    TOKEN_IDENTIFIER, // 2
    TOKEN_ASSIGN, // 3

    TOKEN_NUM, // 4
    TOKEN_CHAR, // 5
    TOKEN_BOOL, // 6

    TOKEN_EOL, // 7
    TOKEN_EOF, // 8

    TOKEN_ADD, // 9
    TOKEN_MINUS, // 10
    TOKEN_MULTIPLY, // 11
    TOKEN_DIVIDE, // 12
    TOKEN_MODULUS, // 13

    TOKEN_GREATER_THAN, // 13
    TOKEN_LESS_THAN, // 14
    TOKEN_COMPARISON, // 15
    TOKEN_GREATER_THAN_EQUAL, // 16
    TOKEN_LESS_THAN_EQUAL, // 17

    TOKEN_IF, // 18
    TOKEN_ELSE, // 19

    TOKEN_BRACKET_OPEN, // 20
    TOKEN_BRACKET_CLOSE, // 21
    TOKEN_SCOPE_BRACKET_OPEN, // 22
    TOKEN_SCOPE_BRACKET_CLOSE, // 23
    TOKEN_COMMA, // 24
    TOKEN_PRIORITY, // 25

    TOKEN_FUNCTION_INITIZLIZER, // 26
    TOKEN_PARAMETERS, // 27
    TOKEN_RETURN, // 28
    TOKEN_FUNCTION_PRINT, // 29
} TokenType;